name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Build Next.js
        run: yarn && yarn build && yarn export
      - name: Build app
        run: cd app && npm i && npm run build

      - name: Upload MacOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: asr-label-macos-arm64.zip
          path: app/dist/asr-label-macos-arm64

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: asr-label-win32-x64.zip
          path: app/dist/asr-label-win32-x64.exe

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: asr-label-linux-x64.zip
          path: app/dist/asr-label-linux-x64
